/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    teams: Team;
    schedule: Schedule;
    standings: Standing;
    sponsors: Sponsor;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    standings: StandingsSelect<false> | StandingsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    about: About;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Administratorius tvarko vartotojus; redaktorius redaguoja tik turinį.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Trumpas paveikslėlio aprašymas prieinamumui ir SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL dalis, pvz. „stovykla-trakuose".
   */
  slug: string;
  /**
   * Naujienos data (svetainėje rodoma lietuviškai). Naujausios rodomos viršuje.
   */
  publishedAt: string;
  excerpt: string;
  photo: number | Media;
  body: string;
  variant?: ('1' | '2') | null;
  /**
   * Kuriam sportui priklauso šis įrašas.
   */
  sport: 'ripka' | 'kyla' | 'ristynes';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  slug: string;
  school: string;
  logo?: (number | null) | Media;
  photo?: (number | null) | Media;
  coach?: string | null;
  players?:
    | {
        name: string;
        role: 'Žaidėjas' | 'Vartininkas' | 'Treneris' | 'Puolėjas' | 'Gynėjas';
        photo?: (number | null) | Media;
        /**
         * Žaidėjo marškinėlių numeris.
         */
        number?: number | null;
        /**
         * Trumpa informacija apie žaidėją, titulai ir t.t.
         */
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  quoteAuthor?: string | null;
  /**
   * Kuriam sportui priklauso šis įrašas.
   */
  sport: 'ripka' | 'kyla' | 'ristynes';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  date: string;
  time?: string | null;
  location: string;
  group?: string | null;
  /**
   * Mažesnis skaičius rodomas pirmiau.
   */
  order?: number | null;
  /**
   * Pasirink komandas iš sąrašo.
   */
  teamRefs?: (number | Team)[] | null;
  teams?:
    | {
        name: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Kuriam sportui priklauso šis įrašas.
   */
  sport: 'ripka' | 'kyla' | 'ristynes';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings".
 */
export interface Standing {
  id: number;
  team: string;
  school?: string | null;
  logo?: (number | null) | Media;
  /**
   * Pvz.: „1-asis pogrūpis", „2-asis pogrūpis", „Finalas", „Pusfinaliai"
   */
  group: string;
  wins?: number | null;
  draws?: number | null;
  losses?: number | null;
  points?: number | null;
  /**
   * Kuriam sportui priklauso šis įrašas.
   */
  sport: 'ripka' | 'kyla' | 'ristynes';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  type: 'sponsor' | 'partner';
  logo: number | Media;
  /**
   * Pvz.: https://example.com — paspaudus logotipą atsidarys ši nuoroda.
   */
  website?: string | null;
  /**
   * Mažesnis skaičius rodomas pirmiau.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'schedule';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'standings';
        value: number | Standing;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  excerpt?: T;
  photo?: T;
  body?: T;
  variant?: T;
  sport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  school?: T;
  logo?: T;
  photo?: T;
  coach?: T;
  players?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        number?: T;
        bio?: T;
        id?: T;
      };
  quote?: T;
  quoteAuthor?: T;
  sport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  date?: T;
  time?: T;
  location?: T;
  group?: T;
  order?: T;
  teamRefs?: T;
  teams?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  sport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings_select".
 */
export interface StandingsSelect<T extends boolean = true> {
  team?: T;
  school?: T;
  logo?: T;
  group?: T;
  wins?: T;
  draws?: T;
  losses?: T;
  points?: T;
  sport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroImage?: (number | null) | Media;
  heroSubtitle?: string | null;
  etnolygaTitle?: string | null;
  etnolygaDescription1?: string | null;
  etnolygaDescription2?: string | null;
  etnolygaPhoto?: (number | null) | Media;
  organizerTitle?: string | null;
  organizerDescription?: string | null;
  organizerPhoto?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  hours?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  timeline?:
    | {
        period: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  gameDescription?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  gameDescriptionPhoto?: (number | null) | Media;
  ripkaToday?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ripkaTodayPhoto?: (number | null) | Media;
  federationUrl?: string | null;
  rules?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  rulesPhoto?: (number | null) | Media;
  rulesUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroImage?: T;
  heroSubtitle?: T;
  etnolygaTitle?: T;
  etnolygaDescription1?: T;
  etnolygaDescription2?: T;
  etnolygaPhoto?: T;
  organizerTitle?: T;
  organizerDescription?: T;
  organizerPhoto?: T;
  email?: T;
  phone?: T;
  hours?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  timeline?:
    | T
    | {
        period?: T;
        text?: T;
        id?: T;
      };
  gameDescription?:
    | T
    | {
        text?: T;
        id?: T;
      };
  gameDescriptionPhoto?: T;
  ripkaToday?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ripkaTodayPhoto?: T;
  federationUrl?: T;
  rules?:
    | T
    | {
        text?: T;
        id?: T;
      };
  rulesPhoto?: T;
  rulesUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}